CREATE TABLE IF NOT EXISTS AUTHOR
(
    ID        INT PRIMARY KEY AUTO_INCREMENT,
    NAME      VARCHAR(30) NOT NULL COMMENT 'Human name',
    COUNTRY   VARCHAR(50) NOT NULL,
    BIRTHDATE DATE
);

CREATE TABLE IF NOT EXISTS PUBLISHER
(
    ID        INT PRIMARY KEY AUTO_INCREMENT,
    NAME      VARCHAR(30) NOT NULL COMMENT 'Company Name',
    COUNTRY   VARCHAR(50) NOT NULL,
    BIRTHDATE DATE
);

CREATE TABLE IF NOT EXISTS BOOK
(
    AUTHOR_ID    INT         NOT NULL,
    PUBLISHER_ID INT,
    NAME         VARCHAR(30) NOT NULL,
    CONTENT      VARCHAR(100),
    PRICE        INT         NOT NULL DEFAULT 0,
    PUBLISHED_AT DATETIME,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID) ON UPDATE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID) ON DELETE CASCADE,
    FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER (ID) ON UPDATE CASCADE,
    FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COUNTRY
(
    ID         INT PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(50) NOT NULL,
    POPULATION LONG        NOT NULL DEFAULT 0 COMMENT 'in 2020',
    LAND_AREA  LONG        NOT NULL DEFAULT 0 COMMENT 'km²',
    DENSITY    INT         NOT NULL DEFAULT 0 COMMENT 'p/km²'
);
